Updates for tero repo.

diff --git a/bin/tatu-build b/bin/tatu-build
--- a/bin/tatu-build
+++ b/bin/tatu-build
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -x
+
 unset CDPATH
 
 GIT_SERVER=github.com
@@ -16,7 +16,28 @@ fi
 
 LOCAL=0
 CLEAN=0
-while getopts ":lca:n:v:" opt; do
+DEFAULT_CODENAME=$REPO_CODENAME
+DEFAULT_ARCH=$ARCH
+
+usage() {
+    cat >&2 <<USAGE
+Uso: ${0} [-c] [-a ARCH] [-l | -n <package name> -v <version>]
+    -a Construir solo para esta arquitectura (por defecto: ${ARCH}).
+    -r Repositorio donde se va a publicar el paquete (por defecto: ${DEFAULT_CODENAME}).
+    -c Borrar el directorio que contiene el código si falla la construcción.
+
+PASAR  
+    -l Construir el paquete a partir del directorio actual.
+O
+    -n Nombre del paquete. El nombre de un repositorio git que será clonado
+       para obtener el código del paquete.
+    -v La versión del paquete a publicar ('latest' para usar el último commit).
+       Indica el tag de git a partir del cual se obtendrá el código del 
+       paquete
+USAGE
+}
+
+while getopts ":hlca:n:v:r:" opt; do
     case $opt in
         a)
             ARCH=$OPTARG
@@ -27,31 +48,29 @@ while getopts ":lca:n:v:" opt; do
         v)
             VERSION=$OPTARG
             ;;
+        r)
+            REPO_CODENAME=$OPTARG
+            ;;
         l)
             LOCAL=1
             ;;
         c)
             CLEAN=1
             ;;
+        h)
+            usage
+            exit 0
+            ;;
          \?)
-           echo "Invalid option: -$OPTARG" >&2
-           ;;
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+            exit 1
+            ;;
     esac
 done
 
-
 if [[ $LOCAL -eq 0  && ($NAME == "" || $VERSION == "") ]]; then
-    cat >&2 <<USAGE
-Usage: ${0} [-c] [-a ARCH] [-l | -n <package name> -v <version>]
-    -a (optional) Architecture. Defaults to 'i386 amd64'.
-    -c (optional) Clean source folder if build for first architecture fails.
-GIVE  
-    -l Build using the current folder.
-OR
-    -n Name of the package. A git repository with that name will be cloned to 
-       get the package sources.
-    -v Version of the package (or 'latest' to use latest on master branch).
-USAGE
+    usage
     exit 1
 fi
 
@@ -60,7 +79,7 @@ VERSION=$(echo $VERSION|tr ':' '_'|tr '~' '_')
 ARCH_LIST=(${ARCH})
 
 if [ "${#ARCH_LIST[@]}" -lt 1 ]; then
-    echo "Must provide at least one architecture." >&2
+    echo "Debe indicar al menos una arquitectura." >&2
     exit 1
 fi
 
@@ -79,11 +98,19 @@ if [[ $LOCAL -eq 0 ]]; then
     # Checkout tag & verify signature.
     if [[ $VERSION != "latest" ]]; then
         echo "Obteniendo tag y verificando firma."
-        git checkout "tags/${VERSION}"
-        git tag -v "${VERSION}"
-        if [ $? -ne 0 ]; then
-            echo "FIRMA INVALIDA. NO SE CONSTRUIRA EL PAQUETE." >&2 && exit 1;
-        fi
+        POSSIBLE_TAGS=(${VERSION} ${REPO_CODENAME}-${VERSION})
+        SELECTED_TAG=
+        for tag in "${POSSIBLE_TAGS[@]}"; do
+             if git rev-parse $tag >/dev/null 2>&1; then
+                 git checkout "tags/${tag}"
+                 [ $? -ne 0 ] && echo "Error: no se pudo obtener el código para el tag '${tag}'." >&2 && exit 1;
+                 git tag -v "${tag}"
+                 [ $? -ne 0 ] && echo "Error: Firma del tag '${tag}' inválida. Asegurese de que la clave GPG pública del desarrollador fue registrada en el servidor de build." >&2 && exit 1;
+                 SELECTED_TAG=${tag}
+                 break
+             fi
+        done
+        [ "${SELECTED_TAG}" == "" ] && echo "No existe un tag para ${POSSIBLE_TAGS[@]}." >&2 && exit 1;
     fi
 fi
 
@@ -102,7 +129,7 @@ if git branch|grep "pristine-tar">/dev/null; then
     sudo GIT_PBUILDER_AUTOCONF=no ARCH="${main_arch}" gbp buildpackage --git-ignore-branch --git-pristine-tar --git-arch="${main_arch}" --git-dist="${BUILD_CODENAME}" \
         --git-builder="pdebuild --architecture ${main_arch} --configfile /etc/pbuilderrc.${main_arch}.tatu --debbuildopts -sa" 
     if [[ $? -ne 0 ]]; then
-        "Fallo la construccion del paquete para la arquitectura '${main_arch}'.">&2
+        "Falló la construcción del paquete para la arquitectura '${main_arch}'.">&2
         if [[ $CLEAN -eq 1 ]]; then        
             rm -rf "${SOURCE_DIR}"
         else
@@ -127,7 +154,7 @@ else
         # Quilt package, get upstream source
         UPSTREAM_VERSION=$(sed -e "s/\(.*\)-.*/\1/" <<< "${VERSION}")
         if [ "$UPSTREAM_VERSION" == "" ]; then 
-            "No se puede determinar la version upstream para ${VERSION}."
+            "No se puede determinar la versión upstream para ${VERSION}."
             exit 1
         fi
         tatu-upstream-get -n "${NAME}" -v "${VERSION}"
@@ -137,7 +164,7 @@ else
     main_arch=${ARCH_LIST[0]}
     sudo ARCH="${main_arch}" pdebuild --architecture ${main_arch} --configfile "/etc/pbuilderrc.${main_arch}.tatu" --debbuildopts -sa 
     if [[ $? -ne 0 ]]; then
-        "Fallo la construccion del paquete para la arquitectura '${main_arch}'.">&2
+        "Falló la construcción del paquete para la arquitectura '${main_arch}'.">&2
         if [[ $CLEAN -eq 1 ]]; then        
             rm -rf "${SOURCE_DIR}"
         else
diff --git a/bin/tatu-publish b/bin/tatu-publish
--- a/bin/tatu-publish
+++ b/bin/tatu-publish
@@ -1,7 +1,8 @@
 #!/bin/bash
-set -x 
+
 #
-# Copies a pdebuild output to the repository staging area, and adds the package to the repository.
+# Construye el paquete en el servidor de build y publica el paquete resultante 
+# en el repositorio.
 # 
 REPO_SERVER=tatumaster.ddns.net
 REPO_USER=root
@@ -23,9 +24,23 @@ fi
 if [ -f ~/.taturepo ]; then
     . ~/.taturepo
 fi
-
+DEFAULT_CODENAME=$REPO_CODENAME
 ONLY_BUILD=0
-while getopts ":ba:n:v:" opt; do
+
+usage() {
+    cat >&2 <<USAGE
+Uso: $0 -n <nombre del paquete> -v <version> [-a ARCH] [-r <codename>] [-b]
+    -a Construir y publicar solo para esta arquitectura (por defecto: ${ARCH}).
+    -r Repositorio donde publicar el paquete (por defecto: ${DEFAULT_CODENAME}).
+    -b Solo construir el paquete, no agregarlo al repositorio.
+    -e Solo intentar exportar los paquetes construidos. Los paquetes ya deben
+       estar disponibles en el servidor.
+USAGE
+}
+
+EXPORT=0
+FORCE_EXPORT=0
+while getopts ":hbefa:n:v:r:" opt; do
     case $opt in
         a)
             ARCH=$OPTARG
@@ -39,50 +54,85 @@ while getopts ":ba:n:v:" opt; do
         b)
             ONLY_BUILD=1
             ;;
+        r)
+            REPO_CODENAME=$OPTARG
+            ;;
+        e)
+            EXPORT=1
+            ;;
+        h)
+            usage
+            exit 0
+            ;;
          \?)
-           echo "Invalid option: -$OPTARG" >&2
-           ;;
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+            exit 1
+            ;;
     esac
 done
 
 if [ "$NAME" = "" -o "$VERSION" = "" ]; then
-    cat >&2 <<USAGE
-Usage: $0 [-a ARCH] -n <package name> -v <version> [-b]
-    -b (optional) Only build the package, do not add it to the repository.
-USAGE
-    exit 1
+    usage;
+    exit 1;
 fi
 
 ARCH_LIST=(${ARCH})
 
 if [ "${#ARCH_LIST[@]}" -lt 1 ]; then
-    echo "Must provide at least one architecture." >&2
+    echo "Debe indicar al menos una arquitectura." >&2
     exit 1
 fi
 
-ssh -t -p ${SSH_PORT} -A ${BUILD_USER}@${BUILD_SERVER} "tatu-build -a '${ARCH}' -n ${NAME} -v ${VERSION}"
-[ $? -ne 0 ] && echo 'Git build failed.' >&2 && exit 1;
-
 FILE_VERSION=${VERSION/[0-9]_/}
+
+export_packages() {
+    echo "Publicando paquetes en el repositorio '${REPO_CODENAME}'."
+    EXPORT_SCRIPT="$(cat <<EOF
+# Configurar el agente para peir el password una sola vez.
+gpg-agent --daemon /bin/bash <<IN_DAEMON_EOF
+for arch in ${ARCH_LIST[@]}; do
+    changes_file="staging-\\\${arch}/${NAME}_${FILE_VERSION}_\\\${arch}.changes"
+    if [ -f ${changes_file} ]; then
+        reprepro --basedir ${REPO_BASEDIR} include ${REPO_CODENAME} \\\${changes_file}
+    else
+        echo "No existe archivo a publicar \\\${changes_file}"
+    fi
+done
+exit
+IN_DAEMON_EOF
+EOF
+)"
+    ssh -t -p ${SSH_PORT} ${REPO_USER}@${REPO_SERVER} "${EXPORT_SCRIPT}"
+}
+
+if [[ ${EXPORT} -eq 1 ]]; then
+   export_packages
+   exit 0
+fi
+
+ssh -t -p ${SSH_PORT} -A ${BUILD_USER}@${BUILD_SERVER} "tatu-build -a '${ARCH}' -n '${NAME}' -v '${VERSION}' -r '${REPO_CODENAME}'"
+[ $? -ne 0 ] && echo 'Falló la construcción del paquete.' >&2 && exit 1;
+
 
 # Copy built files to repository server for publishing.
 TEMP_BUILD_DIR=`mktemp -d`
 for arch in "${ARCH_LIST[@]}"; do
+    echo "Copiando archivos creados al equipo local bajo '${TEMP_BUILD_DIR}/${arch}'."
     mkdir ${TEMP_BUILD_DIR}/${arch}
     scp -P ${SSH_PORT} ${BUILD_USER}@${BUILD_SERVER}:${BUILD_BASEDIR}/${BUILD_CODENAME}-${arch}/result/${NAME}*${FILE_VERSION}[_.]* ${TEMP_BUILD_DIR}/${arch}/ 2>&1
     scp -P ${SSH_PORT} ${BUILD_USER}@${BUILD_SERVER}:${BUILD_BASEDIR}/${BUILD_CODENAME}-${arch}/result/${NAME}*.tar.* ${TEMP_BUILD_DIR}/${arch}/ 2>&1
     if [ $? -ne 0 ]; then 
-        echo "No files for ${arch} architecture."
+        echo "No se crearon archivos para la arquitectura '${arch}'."
         rm -rf ${TEMP_BUILD_DIR}/${arch}
     else 
-        echo "Copying built files to server staging area."
+        echo "Copiando archivos creados al repositorio bajo '${REPO_USER}@${REPO_SERVER}:staging-${arch}/'."
         scp -P ${SSH_PORT} ${TEMP_BUILD_DIR}/${arch}/* ${REPO_USER}@${REPO_SERVER}:staging-${arch}/
     fi
 done
 
 if [[ ${ONLY_BUILD} -eq 0 ]]; then
-
-    # Copy tatu-repo & tatu-repo-update to HTTP server root folder, and link current published version.
+    # Copiar tatu-repo & tatu-repo-update a la raíz del servidor HTTP, y crear un link a la última versión.
     if [ "${NAME}" = "tatu-repo" -o "${NAME}" = "tatu-repo-update" ]; then
 	    ssh -t -p ${SSH_PORT} ${REPO_USER}@${REPO_SERVER} 'bash -sh'<<EOF
 cp staging-${ARCH_LIST[0]}/${NAME}_${FILE_VERSION}_all.deb ${REPO_WEBROOT};
@@ -90,12 +140,8 @@ ln -f -s ${REPO_WEBROOT}/${NAME}_${FILE_VERSION}_all.deb ${REPO_WEBROOT}/${NAME}
 EOF
     fi
 
-    [ $? -ne 0 ] && echo 'Copy to server staging area failed.' >&2 && exit 1;
-    for arch in "${ARCH_LIST[@]}"; do
-        if [ -d ${TEMP_BUILD_DIR}/${arch}/ ]; then
-	        ssh -t -p ${SSH_PORT} ${REPO_USER}@${REPO_SERVER} "reprepro --basedir ${REPO_BASEDIR} include ${REPO_CODENAME} staging-${arch}/${NAME}_${FILE_VERSION}_${arch}.changes"
-        fi
-    done
+    [ $? -ne 0 ] && echo 'Falló la copia al repositorio.' >&2 && exit 1;
+    export_packages
 fi
 
 rm -rf ${TEMP_BUILD_DIR}
diff --git a/bin/tatu-release b/bin/tatu-release
--- a/bin/tatu-release
+++ b/bin/tatu-release
@@ -1,7 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 
 #
-# Releases the package and tags the repository.
+# Libera una nueva versión del paquete.
+# Agrega un tag con <repo>-<version> y publica los cambios a git.
 #
 
 if [ -f /etc/taturepo.conf ]; then
@@ -12,9 +13,48 @@ if [ -f ~/.taturepo ]; then
     . ~/.taturepo
 fi
 
+if [ ! -d './debian' ]; then
+	echo -e "Error: No existe el directorio './debian'.\nEjecute el comando en la raíz del paquete." >&2
+        exit 1;
+fi 
+
+if [ ! -e './debian/changelog' ]; then
+	echo -e "Error: No existe el archivo './debian/changelog'." >&2
+        exit 1;
+fi 
+
+if [ ! -d './.git' ]; then
+	echo -e "Error: No es un repositorio de git." >&2
+        exit 1;
+fi 
+
+if [ "$(git status --porcelain)" != "" ]; then
+	echo -e "Error: Hay cambios pendientes.\nEjecutar 'git status' para verlos.\nTodos los cambios deben ser revertidos/confirmados antes de hacer un release." >&2
+        exit 1;
+fi
+
+LAST_DISTRO=$(dpkg-parsechangelog --show-field Distribution)
+if grep "${LAST_DISTRO}" /usr/share/lintian/vendors/ceibal/main/data/changes-file/known-dists>/dev/null; then
+    REPO_CODENAME=$LAST_DISTRO
+fi
+
+DEFAULT_CODENAME=$REPO_CODENAME
+
 INCREMENT=0
 FORCE=0
-while getopts ":fi" opt; do
+
+usage() {
+      cat >&2 <<USAGE
+Libera una nueva versión de un paquete.
+Uso: $0 [-i] [-f] [-r]
+    -i Incrementar la versión en debian/changelog y luego liberar.
+    -f Agregar tag y publicar a git, aun si el changelog no está marcado 
+       como UNRELEASED.
+    -r Repositorio donde se va a publicar el paquete (por defecto: ${DEFAULT_CODENAME}).
+USAGE
+}
+
+while getopts ":hfi" opt; do
   case $opt in
     i)
       INCREMENT=1
@@ -22,43 +62,41 @@ while getopts ":fi" opt; do
     f)
       FORCE=1
       ;;
-    \?)
-      cat >&2 <<USAGE
-Usage: $0 [-i|-f]
-    -i Increment changelog and then release.
-    -f Force tag creation even if changelog is not marked as UNRELEASED.
-USAGE
-      exit 1
+    r)
+      REPO_CODENAME=$OPTARG
       ;;
+    h)
+      usage
+      exit 0
+      ;;
+    \?)
+      echo "Opción inválida: -$OPTARG" >&2
+      usage
+      exit 1
   esac
 done
 
-if [ ! -d './debian' ]; then
-	echo "Error: No existe el directorio './debian'.\nEjecute el comando en la raíz del paquete." >&2 && exit 1;
-fi 
-
-if [ ! -e './debian/changelog' ]; then
-	echo "Error: No existe el archivo './debian/changelog'." >&2 && exit 1;
-fi 
-
-if [ ! -d './.git' ]; then
-	echo "Error: No es un repositorio de git." >&2 && exit 1;
-fi 
-
-if [ "$(git status --porcelain)" != "" ]; then
-	echo "Error: Hay cambios pendientes.\nEjecutar 'git status' para verlos.\nTodos los cambios deben ser revertidos/confirmados antes de hacer un release." >&2 && exit 1;
-fi
-
-if [ "${INCREMENT}" -eq 0 ]; then
-	if [ "$(dpkg-parsechangelog --show-field Distribution)" != "UNRELEASED" -a "$FORCE" -ne 1 ]; then
-		echo "Error: El paquete no esta marcado como UNRELEASED.\nPase la opción '-i' o ejecute 'dch -i' para incrementar la version antes de hacer un release." >&2 && exit 1;
-	fi
-else
-	dch -i ${DCH_OPTIONS}
-fi
+LOCAL=$(git rev-parse @)
+REMOTE=$(git rev-parse @{u})
+BASE=$(git merge-base @ @{u})
+test $REMOTE = $BASE
+MUST_PUSH=$?
 
 CHANGELOG_DATE=$(stat --printf='%Y' ./debian/changelog)
-dch -r ${DCH_OPTIONS}
+if [ "${INCREMENT}" -eq 0 ]; then
+	if [ "${LAST_DISTRO}" != "UNRELEASED" -a "$FORCE" -ne 1 ]; then
+      		cat >&2 <<ERROR
+Error: El paquete no está marcado como UNRELEASED en debian/changelog.
+Si está intentando re-liberar un paquete que falló al firmarse o publicarse a git, pase la opción '-f' para ignorar este error.
+Si está intentando liberar un nueva versión de un paquete, pase la opción '-i', o ejecute 'dch -i' para incrementar la versión antes de hacer una liberación.
+ERROR
+                exit 1
+	fi
+	dch -r -D ${REPO_CODENAME} ${DCH_OPTIONS}
+else
+	dch -i -D ${REPO_CODENAME} ${DCH_OPTIONS}
+fi
+
 if [ "${CHANGELOG_DATE}" -eq "$(stat --printf='%Y' ./debian/changelog)" ]; then
 	echo "Debe actualizar o grabar el archivo de changelog." >&2 && exit 1;
 fi
@@ -73,13 +111,19 @@ VERSION=$(dpkg-parsechangelog --show-field Version|tr ':' '_'|tr '~' '_')
 git add ./debian/changelog
 [ $? -ne 0 ] && exit 1;
 
-git commit -m "Updated changelog for release."
+LAST_MESSAGE=$(git log -1 --pretty=%B)
+NEW_MESSAGE="Se actualizó el changelog para versión ${REPO_CODENAME}-${VERSION}."
+
+if [ "${LAST_MESSAGE}" -eq  "${NEW_MESSAGE}" -a $MUST_PUSH ]; then
+    git commit --amend -m "${NEW_MESSAGE}"
+else
+    git commit -m "${NEW_MESSAGE}"
+fi
 [ $? -ne 0 ] && exit 1;
 
-git push
+TAGNAME=${REPO_CODENAME}-${VERSION}
+git tag -s "${TAGNAME}" -m "Versión ${VERSION} para ${REPO_CODENAME}"
 [ $? -ne 0 ] && exit 1;
 
-git tag -s "${VERSION}" -m "Release of ${VERSION}"
+git push origin HEAD "${TAGNAME}"
 [ $? -ne 0 ] && exit 1;
-
-git push origin "${VERSION}"
