Fixes & add -b option to publish.

diff --git a/bin/tatu-publish b/bin/tatu-publish
--- a/bin/tatu-publish
+++ b/bin/tatu-publish
@@ -23,7 +23,8 @@ if [ -f ~/.taturepo ]; then
     . ~/.taturepo
 fi
 
-while getopts ":a:n:v:" opt; do
+ONLY_BUILD=0
+while getopts ":ba:n:v:" opt; do
     case $opt in
         a)
             ARCH=$OPTARG
@@ -34,6 +35,9 @@ while getopts ":a:n:v:" opt; do
         v)
             VERSION=$OPTARG
             ;;
+        b)
+            ONLY_BUILD=1
+            ;;
          \?)
            echo "Invalid option: -$OPTARG" >&2
            ;;
@@ -42,7 +46,8 @@ done
 
 if [ "$NAME" = "" -o "$VERSION" = "" ]; then
     cat >&2 <<USAGE
-Usage: $0 [-a ARCH] -n <package name> -v <version>  
+Usage: $0 [-a ARCH] -n <package name> -v <version> [-b]
+    -b (optional) Only build the package, do not add it to the repository.
 USAGE
     exit 1
 fi
@@ -62,15 +67,18 @@ for arch in "${ARCH_LIST[@]}"; do
 	scp ${BUILD_USER}@${BUILD_SERVER}:${BUILD_BASEDIR}/${BUILD_CODENAME}-${arch}/result/${NAME}_${VERSION}[_.]* ${REPO_USER}@${REPO_SERVER}:staging-${arch}/
 done
 
-# Copy tatu-repo & tatu-repo-update to HTTP server root folder, and link current published version.
-if [ "${NAME}" = "tatu-repo" -o "${NAME}" = "tatu-repo-update" ]; then
-	ssh ${REPO_USER}@${REPO_SERVER} 'bash -sh'<<EOF
+if [[ ${ONLY_BUILD} -eq 0 ]]; then
+
+    # Copy tatu-repo & tatu-repo-update to HTTP server root folder, and link current published version.
+    if [ "${NAME}" = "tatu-repo" -o "${NAME}" = "tatu-repo-update" ]; then
+	    ssh ${REPO_USER}@${REPO_SERVER} 'bash -sh'<<EOF
 cp staging-${ARCH_LIST[0]}/${NAME}_${VERSION}_all.deb ${REPO_WEBROOT};
 ln -f -s ${REPO_WEBROOT}/${NAME}_${VERSION}_all.deb ${REPO_WEBROOT}/${NAME}.deb
 EOF
-fi
+    fi
 
-[ $? -ne 0 ] && echo 'Copy to server staging area failed.' >&2 && exit 1;
-for arch in "${ARCH_LIST[@]}"; do
-	ssh ${REPO_USER}@${REPO_SERVER} "reprepro --basedir ${REPO_BASEDIR} include ${REPO_CODENAME} staging-${arch}/${NAME}_${VERSION}_${arch}.changes"
-done
+    [ $? -ne 0 ] && echo 'Copy to server staging area failed.' >&2 && exit 1;
+    for arch in "${ARCH_LIST[@]}"; do
+	    ssh ${REPO_USER}@${REPO_SERVER} "reprepro --basedir ${REPO_BASEDIR} include ${REPO_CODENAME} staging-${arch}/${NAME}_${VERSION}_${arch}.changes"
+    done
+fi
