Use cowbuilder and build locals.

diff --git a/tatu-build b/tatu-build
--- a/tatu-build
+++ b/tatu-build
@@ -10,7 +10,8 @@ if [ -e ~/.taturepo ]; then
     . ~/.taturepo
 fi
 
-while getopts ":a:n:v:" opt; do
+LOCAL=0
+while getopts ":la:n:v:" opt; do
     case $opt in
         a)
             ARCH=$OPTARG
@@ -21,14 +22,27 @@ while getopts ":a:n:v:" opt; do
         v)
             VERSION=$OPTARG
             ;;
+        l)
+            LOCAL=1
+            ;;
          \?)
            echo "Invalid option: -$OPTARG" >&2
            ;;
     esac
 done
 
-if [ "$NAME" = "" -o "$VERSION" = "" ]; then
-    echo "Usage: $0 [-a ARCH] -n <package name> -v <version>" >&2
+
+if [[ $LOCAL -eq 0  && ($NAME == "" || $VERSION == "") ]]; then
+    cat >&2 <<USAGE
+Usage: ${0} [-a ARCH] [-l | -n <package name> -v <version>]
+    -a (optional) Architecture. Defaults to 'i386 amd64'.
+GIVE  
+    -l Build using the current folder.
+OR
+    -n Name of the package. A git repository with that name will be cloned to 
+       get the package sources.
+    -v Version of the package.
+USAGE
     exit 1
 fi
 
@@ -39,18 +53,21 @@ if [ "${#ARCH_LIST[@]}" -lt 1 ]; then
     exit 1
 fi
 
-# Create temporary folder for git clone
-SOURCE_DIR=$(mktemp --tmpdir -d "build-${NAME}_${VERSION}-XXXXXX")
-cd "${SOURCE_DIR}"
+if [[ $LOCAL -eq 0 ]]; then
 
-# Get git repository
-git clone git://${GIT_SERVER}${GIT_BASE}${NAME}.git;
-cd "${NAME}"
+    # Create temporary folder for git clone
+    SOURCE_DIR=$(mktemp --tmpdir -d "build-${NAME}_${VERSION}-XXXXXX")
+    cd "${SOURCE_DIR}"
 
-# Verify tag signature.
-git tag -v "${VERSION}"
-if [ $? -ne 0 ]; then
-	echo "FIRMA INVALIDA. NO SE CONSTRUIRA EL PAQUETE." >&2 && exit 1;
+    # Get git repository
+    git clone git://${GIT_SERVER}${GIT_BASE}${NAME}.git;
+    cd "${NAME}"
+
+    # Verify tag signature.
+    git tag -v "${VERSION}"
+    if [ $? -ne 0 ]; then
+	    echo "FIRMA INVALIDA. NO SE CONSTRUIRA EL PAQUETE." >&2 && exit 1;
+    fi
 fi
 
 ARCH_INDEP=1
